monitor:
  fixed-rate: 3000

directory:
  in: '${user.home}\data\in'
  out: '${user.home}\data\out'
  processing: '${user.home}\data\processing'
  processed: '${user.home}\data\processed'
  error: '${user.home}\data\error'

parser:
  character:
    standard: 'รง'
    items: ','
    item: '-'

supported-file:
  extensions:
  - 'dat'